### ISSUE TITLE
"/var/lib/dokku/config" does not exist, should I create?

### ISSUE THREAD

**Issue by busla** [josegonzalez/dokku-global-cert#1]
Figured out that I could use this plugin instead of manually setting the SSL cert globally on my dokku host using this guide: http://dokku.viewdocs.io/dokku~v0.4.6/deployment/ssl-configuration/

`/var/lib/dokku/config` does not exist so I guess I need to create that directory? I ask since there is also a *config* directory in `/var/lib/dokku/plugins/enabled`

Cheers!

**Comment by josegonzalez** [comment]
Plugin requires Dokku 0.7.0+, please upgrade to that first.

**Comment by busla** [comment]
ok, I´ve got 0.9.1.

So I need to add that directory then?

**Comment by josegonzalez** [comment]
Guess I had another plugin that created that directory.

Fixed in 9d30d5f2267312edbebee30c184f159e9e2a46d2.
